---
# This playbook deploys the whole basic stack.

- name: install basic deb packages
  hosts: all
  remote_user: gdsupport
  roles:
    - common_install


- name: apply ntp configuration to all nodes
  hosts: all
  remote_user: gdsupport
  
  roles:
    - ntpd

#- name: configure and deploy the webservers and application code
#  hosts: webservers
#  remote_user: gdsupport

#  roles:
#    - web

#- name: deploy MySQL and configure the databases
#  hosts: dbservers
#  remote_user: root

#  roles:
#    - db